# Generated by Django 5.2.11 on 2026-05-07 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('methode', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money'), ('ESPECES', 'Espèces')], max_length=50)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé')], default='EN_ATTENTE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental')),
            ],
        ),
    ]
