# Generated by Django 5.2.11 on 2026-05-08 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rental',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.rental'),
        ),
    ]
