# Generated by Django 5.2.11 on 2026-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_blocked',
            new_name='is_walk_in',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='adresse',
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
