# Generated by Django 5.2.11 on 2026-05-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('immatriculation', models.CharField(max_length=100, unique=True)),
                ('type_vehicule', models.CharField(choices=[('SUV', 'SUV'), ('BERLINE', 'Berline'), ('4X4', '4X4'), ('SPORT', 'Sport'), ('UTILITAIRE', 'Utilitaire')], max_length=50)),
                ('prix_location', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LOUE', 'Loué'), ('MAINTENANCE', 'Maintenance'), ('VENDU', 'Vendu')], default='DISPONIBLE', max_length=50)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
